### PR TITLE
Initial support for PostgreSQL

### PR DESCRIPTION
**Pull request by ammachado**

### CODE REVIEW

**Comment by tylercd100** [comment]
Is there anyway I can help to speed this along? I would very much like to use db-dumper for postgres

**Comment by ammachado** [comment]
Hello Tyler,
Seems to me that it's done.  I'd like to integrate it to https://github.com/spatie/laravel-backup, but I'll wait for a official release of this pull request before changing it.

Date: Fri, 11 Mar 2016 15:08:49 -0800

**Comment by tylercd100** [comment]
Awesome! That is also my intent. I created a fork for db-dumper this morning only to realize the existence of your fork. Anyways, i'll be here for support if its needed. Thanks for putting the work in @ammachado, once the request is accepted this will help me a ton!

**Comment by freekmurze** [comment]
Thank you very much for your contribution. :+1:  There are a few things I'd like to do differently, but I'll make those changes myself.

**Comment by freekmurze** [comment]
The cleaned up code is now ready in master branch. Unless you find any problems, it'll be tagged soon as a new version.

**Pull request merged**
