### PR TITLE
fix: add some public functions that allow extensibility

### PR DESCRIPTION
**Pull request by jpswade**
I wanted to make this more extensible so I had a way I could get the process back and watch the progress, eg:

```
$process = $this->dumpToFile($mysqlDumper, $outputFile);
$process->start();
$this->output->progressStart();
while ($process->isRunning()) {
            sleep(1);
            clearstatcache(true, $outputFile);
            $size = filesize($outputFile);
            $this->output->progressAdvance($size);
}
$this->output->progressFinish();
```

This means I can now add a progress bar

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by rognales** [comment]
Hi, this PR seems to be the point of the issues here on laravel-backup pagkage https://github.com/spatie/laravel-backup/issues/1218

`````
mysqldump: [ERROR] Failed to open required defaults file: C:\Users\User\AppData\Local\Temp\php52A2.tmp
mysqldump: [ERROR] Fatal error in defaults handling. Program aborted!
`````

**Comment by freekmurze** [comment]
I will revert the changes of this PR as the changes seem to cause problems.

**Comment by rognales** [comment]
@freekmurze hi freek. Yes, 2.20 is now successfully backed up my apps.

Thx for the prompt responses

**Comment by jpswade** [comment]
> Hi, this PR seems to be the point of the issues here on laravel-backup pagkage [spatie/laravel-backup#1218](https://github.com/spatie/laravel-backup/issues/1218)
> 
> ```
> mysqldump: [ERROR] Failed to open required defaults file: C:\Users\User\AppData\Local\Temp\php52A2.tmp
> mysqldump: [ERROR] Fatal error in defaults handling. Program aborted!
> ```

That’s really strange. Logically I’ve not really changed anything apart from tighten up some types.

All tests pass so I wonder if it’s something specific to your environment?

What are you running?

**Comment by jpswade** [comment]
@rognales I've give it another go, would you be able to test this to confirm that it doesn't cause a problem for you?

https://github.com/spatie/db-dumper/pull/141/files

**Comment by rognales** [comment]
@jpswade nope. the error return with https://github.com/spatie/db-dumper/pull/141

My machine:-

Windows x64
PHP 7.4.12
Laravel Framework 7.30.4

**Comment by jpswade** [comment]
Hi @rognales thanks for that. I have a theory that the method that contains the `tmpfile()` function is closing the file resource and thus removing the temp file.

I've moved the creation of `tmpfile()` up, and made it a property on the class, so hopefully that will force it to stay around.

Would you be so kind as to give it another go?

**Pull request merged**
