### PR TITLE
fix: make the process more extensible, avoid touching anything

### PR DESCRIPTION
**Pull request by jpswade**
I wanted to make this more extensible so I had a way I could get the process back and watch the progress.

Unfortunately I must have changed too much in the last PR which seemed to break a few instances.

I've touched less in this one, literally nothing has changed other than moving logic around and changing the accessibility of methods.

Here's an example of how this can be used:

```
<?php

include '../vendor/autoload.php';

use Spatie\DbDumper\Databases\MySql;

$host = 'test';
$filename = 'example.sql';
$outputFile = $filename;
$host = '127.0.0.1';
$schemaName = 'test';
$userName = 'root';
$password = '';

$mysqlDumper = MySql::create()
    ->setHost($host)
    ->setDbName($schemaName)
    ->setUserName($userName)
    ->setPassword($password)
    ->setGtidPurged('OFF');

$process = $mysqlDumper->getProcess($outputFile);
$process->start();
while ($process->isRunning()) {
    sleep(1);
    clearstatcache(true, $outputFile);
    $size = filesize($outputFile);
    echo $size . PHP_EOL;
}
```

Only, imagine instead of `echo $size`, you replace that with a progress bar, which isn't available in this package.

For example:

```
$process = $mysqlDumper->getProcess($outputFile);
$process->start();
$this->output->progressStart();
while ($process->isRunning()) {
            sleep(1);
            clearstatcache(true, $outputFile);
            $size = filesize($outputFile);
            $this->output->progressAdvance($size);
}
$this->output->progressFinish();
```

Apologise if the previous change had a negative impact, hopefully this doesn't.

### CODE REVIEW

**Comment by freekmurze** [comment]
I'll merge this in when others confirm that it doesn't break anything.

**Comment by jpswade** [comment]
Understandable. Thanks @freekmurze. Apologise for that, not sure why it would have caused such an issue as very little has really changed as you can see.

**Comment by freekmurze** [comment]
No apologies needed, these things can happen. I also don't understand what was going wrong, but something unintended was clearly happening with the changes in previous PR.

**Comment by oriceon** [comment]
@jpswade It`s about tmpfile()

**Comment by jpswade** [comment]
Thanks @oriceon I believe that’s fixed now. Have you tried this branch/PR?

**Comment by oriceon** [comment]
@jpswade yes, now it`s workin. Thanks for pr.

**Comment by jpswade** [comment]
Great news, thanks @oriceon.

**Comment by rognales** [comment]
Hi @jpswade , this updated PR working as expected.

Sorry for late response.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
